### ISSUE TITLE
crypto/fiat conversion search terms

### ISSUE THREAD

**Issue by joshtom1** [PresearchOfficial/presearch-packages#136]
**Describe the bug**
The crypto/fiat conversion search can be incorrect.

**To Reproduce**
![image](https://user-images.githubusercontent.com/25560722/159286728-99570d1d-6963-4218-9b47-aa61f3687f13.png)

**Expected behavior**
The search should be more precise.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.36.116

**Smartphone (please complete the following information):**
N/A

**Additional context**
I built a currency converter in Nov, but it appears not to be used. I think the search was a little more precise. If you found something wrong, I would have been happy to fix but I didn't receive much feedback. I guess I'm curious why my package was not used.

I was out for a month because of covid, but other than that I have been following the project. I sent an email and created a pull request. This is the only response I got, but I assumed everything was okay:
![image](https://user-images.githubusercontent.com/25560722/159288218-1b3b2052-35eb-4bb6-a2bc-b62e0f44991f.png)

I wanted to contribute because I was passionate about the project and wanted to help. It was not for fame or economic incentives but I must admit it is a little weird to see the same package built by a different developer, later on, and with less features.

I was just searching for cpus and not trying to purposefully find an issue with the new converter.

Here is part of the email I wrote to the dev team that shows some of the features:
![image](https://user-images.githubusercontent.com/25560722/159290684-4f7e3237-9b7c-4a84-b3af-75e9674b85c9.png)

Here are the results with the current converter:
![image](https://user-images.githubusercontent.com/25560722/159290831-684f5544-a843-4311-a963-c7ea8994a2be.png)

![image](https://user-images.githubusercontent.com/25560722/159290894-ae5d3ab9-fe82-49a3-82cd-b167cd6aa93a.png)

![image](https://user-images.githubusercontent.com/25560722/159290949-03429afb-d3ca-4902-8333-7ed1ac08aab6.png)

The search term doesn't always trigger:
![image](https://user-images.githubusercontent.com/25560722/159291739-b99fcb26-b289-423c-8707-11daaa879359.png)
![image](https://user-images.githubusercontent.com/25560722/159291866-4d233631-f684-4204-a401-d7a2fd8919c1.png)

**Comment by joshtom1** [comment]
The nzd to sol conversion seems consistent today. Maybe it was an issue with the api the other day.

**Comment by jejopl** [comment]
Hey @joshtom1, first of all - I'm really sorry that I've missed your email - my bad 🙏. 

About this situation, since both packages could be triggered with the same query, we have decided to go with `currencyConverter` package, since it has 'all in one' functionality. We wanted to avoid the situation where query can trigger more than one package. I agree that yours is more efficient, for cryptocurrency conversions. I've improved the test environment and now, you will receive a warning message, when the query will trigger a different package, than that you are working on (it will be pushed to github soon, need to do some final tweaks)

End of the year was pretty busy for us, we had a lot of things going on and there wasn't enough time to cover the packages. 

Recently, we have changed the approach and now, we want to focus more on the packages. There's a new discord channel, dedicated to presearch-packages and it would be cool if you could join us as well - https://discord.gg/ErehmHWk

Decision to temporarily remove your package was made, since it was quicker to do it than refactor both of the packages.
We wanted to keep consistency between the layout, so the package should look very similar for crypto and fiat conversions. Now I can see that this decision was bad and not fair. I want to apologize you, since I'm responsible for the packages and it was mostly my personal call. In the future, we will want to have a place, where the community could vote for their favorite package

We will keep both of the packages, I'll remove the crypto functionality from `currencyConverter` package, and the queries for crypto conversion, should now trigger only `cryptoConverter` package. 

It would be cool if you could change the styling of your package and make it look similar to `currencyConverter` package. Let me know if you are willing to do this change.

**Comment by jejopl** [comment]
Yeah, I've talked with the team and we decided that we will combine those two packages into one. We will use trigger function from `cryptoConverter` and the rest from `currencyConverter`

**Comment by jejopl** [comment]
Hey @joshtom1, closing this one since we merged those two packages into one, and added you as co-author

**Comment by joshtom1** [comment]
Sounds good.

I've been thinking about this for a while. It should be 1 package because it should be able to handle fiat to crypto conversions.

Also, I was thinking of holding off on working on this for 2 reasons. 1 - I don't want to interfere with Niklas ability to quickly add features, etc... 2 - I am in the job market and I want to avoid a potential conflict of interest.

I don't need to be made a co-author :). Feel free to use whatever features you like in my old code.

I look forward to using the new conversion package on presearch. There is also potential to have conversions for various other common finanical assets like commodities/metals. I look forward to seeing how this evolves.
