### ISSUE TITLE
Calculator calcs wrong

### ISSUE THREAD

**Issue by LightTemplar** [PresearchOfficial/presearch-packages#168]
**Describe the bug**
Enter 37.8+2.9 in the search field, calculator gives:
= 40.699999999999996

**Expected behavior**
The result should be: 40.7

**Screenshots**
![image](https://user-images.githubusercontent.com/453783/191828239-dba49700-d534-439c-bfd6-a83784211fde.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Brave [Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**
Nothing more

**Comment by manolinux** [comment]
> 37.8+2.9

I think all math in the calculator should be implemented using a BigDecimal type, because Javascript's limited floating point math (IEEE-754) has this surprises, some numbers that can't be accurately represented. Same happened in Java, they included BigDecimal for arbitrary precission. An example library in JS that does the same:
https://github.com/iriscouch/bigdecimal.js

**Comment by manolinux** [comment]
The package seems to do two things:

- First time it uses node mathjs to evaluate the expression. But mathjs seems not to be using BigNumbers.
- Next times, if our calculations are done by pushing calculator buttons, then the result is calculated dynamically, but uses Javascript float, which we know can lead to aproximate but not exact results.

We han handle both things:
- By telling mathjs to use BigNumbers
- By creating a dynamic script tag, we can load https://cdnjs.cloudflare.com/ajax/libs/big.js/2.3.0/big.min.js, for managing BigNumbers, then the dynamic results are done with the Big type from that package.

I include sample index.js for math package that seems to work (renamed to index.js.txt so that it's accepted here). 

[index.js.txt](https://github.com/PresearchOfficial/presearch-packages/files/9960614/index.js.txt)

Give me permissions (if you feel like) for creating a branch and doing a PR.
Kind regards!

**Comment by jejopl** [comment]
Thanks @manolinux! Can you fork the repo, create a branch and then do a pull request? 
This is the way to contribute to presearch-packages repo

**Comment by jejopl** [comment]
Closing this one because it has been fixed by @manolinux. It will be pushed to production soon, thanks guys!
