### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by mad409** [PresearchOfficial/presearch-packages#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

The color picker isn't working, or displaying correctly.

**Comment by mad409** [comment]
Color picker still not displaying correctly on pages.

**Comment by jejopl** [comment]
@davidkeefe24 there's still a problem with color picker package. It looks like, the JavaScript is not invoked. This is how color picker looks currently:
######
![obraz](https://user-images.githubusercontent.com/32012330/71600186-2bc51080-2b4e-11ea-950f-f41d0cf3c101.png)
#####
_________________
The JavaScript that should do the magic is there but it looks like it's not triggered:
######
![obraz](https://user-images.githubusercontent.com/32012330/71600230-5ca54580-2b4e-11ea-94ce-f95b61d761a2.png)
######
____________________
But if I just copy the script I wrote from above to the console, everything works fine:
######
![obraz](https://user-images.githubusercontent.com/32012330/71600283-8e1e1100-2b4e-11ea-944a-314c42aa7376.png)
######
_________
I don't know how to fix it because there's no errors and everything works fine on the test environment.

**Comment by davidkeefe24** [comment]
@jejopl That is correct. Currently, the frontend site will not execute JS in those packages. This is something I am working to add functionality for, as well as improving triggers and passing of trigger data in a future release.

**Comment by davidkeefe24** [comment]
@jejopl I have your color picker working on my DSearch development branch. Going to do a little bit more testing this week but it should be good to go soon. See the attached video example.

[Screen Recording 2020-03-31 at 3.33.19 PM.zip](https://github.com/PresearchOfficial/presearch-packages/files/4411215/Screen.Recording.2020-03-31.at.3.33.19.PM.zip)

**Comment by jejopl** [comment]
That's awesome :-)) Great work @davidkeefe24! Can't wait to see it online!

**Comment by davidkeefe24** [comment]
@jejopl This has gone live on both dsearch.com and engine.presearch.org 

Let me know if all looks good and I will close this issue.

**Comment by mad409** [comment]
Nice, looks and works great! Thanks...

**Comment by jejopl** [comment]
> 
> 
> @jejopl This has gone live on both dsearch.com and engine.presearch.org
> 
> Let me know if all looks good and I will close this issue.

Looks good, it's working :-)
