### ISSUE TITLE
SUGGESTION: Improve Presearch's UI/UX experience.

### ISSUE THREAD

**Issue by Raceee1** [PresearchOfficial/presearch-packages#91]
Hello Dev Team!

Understand that things like main-net is in our priority but here are a few things that should be finished and implemented on Presearch to make it feel more modern and improve it's usability.

- Presearch's search result page has recieved the new UI redesign, but the **homepage still carries the old design** on presearch.org, please implement the new UI on homepage as well from engine.presearch.org

- Please link the privacy policy and terms of service under the page in presearch so users can get easy access to these legal documents, why does it matter? New users coming to presearch might want to know how serious we are in-terms of privacy, and they will search for our privacy policy to know more. Right now, it's harder to find it, as you will have to go on your account and do it. Please add it like other search engines have (ie: brave search).
![Capture](https://user-images.githubusercontent.com/94134265/141347159-d3fcd384-d469-49f3-941d-502d96456673.PNG)

- I am not very sure about this, but it seems like presearch isn't completely open source, as some parts are not open sourced yet, we should also focus on open sourcing the whole search engine, huge thing that will draw FOSS and privacy users.

- We should completely migrate from presearch.org to ".com"

Thank you so much! Hope this can be looked into!
@treygrainger @jejopl @colinpape

**Comment by treygrainger** [comment]
Hi @Raceee1.

Most of the things you mentioned are on the near-term roadmap or already being worked on:
1) integrating the engine.presearch.org homepage to become the new presearch.org homepage.
2) migrating from presearch.org to presearch.com

We're also reworking the menus across the entire platform to have a newer, consistent design, in which the privacy policy and terms will be linked prominently from all pages.

re: open sourcing, different parts of the platform are being open sourced at different paces, due to a combination of privacy reasons, competitive reasons, and overall focus on go to market strategy. Core parts of the system (user account information, payment portals, crypto processing, etc.) are systems that won't be open source and will instead need to be reworked to integrate in a pluggable fashion into the open source components later. We've talked a bit about the open source strategy in the vision paper, but different systems will become open source at different rates and the community grows and the platform matures and reaches critical mass.

For now, all of the presearch-packages are all open sourced, and you can contribute here. Things like our crawler should get open sourced sooner than other components since there are less privacy concerns there, and nodes, gateways, and webservers will come later on the roadmap due to the need to build some new kinds of privacy mechanisms into them before it's safe for them to run in the wild. We don't want people running forks of the platform and tracking users and building profiles / selling that data and being malicious. Those are not problems it makes sense for the project to get side-tracked on right now while we are in growth mode and preparing for mainnet launch - too many other critical things to get right first. It will come, but it's a long roadmap to get there.

Thanks for the feedback!

**Comment by Raceee1** [comment]
Hello Trey,

Thanks for the reply, great to know all of these is already under the radar.

**Comment by JoshuaPaulBarnard** [comment]
Hey @Raceee1!

Presearch has been able to implement almost all your idea's and suggestions in the last few years!  

1. The new UI has been launched and is looking great!  With options for dark/light mode and lots of modern features.  

2. We took your advice seriously and have added our Privacy Policy to the bottom of every front page and search result.  
![image](https://github.com/PresearchOfficial/presearch-packages/assets/20632243/b17b49bf-7323-4176-a171-83d058094f40)
![image](https://github.com/PresearchOfficial/presearch-packages/assets/20632243/cdcd3aaf-4d62-4212-b8f9-d7c777a44c9e)

3. We are working towards making the worlds first decentralized open-source web crawler, though we don't have an exact release date for that yet.  

4. We have completely migrated over from .org to .com, to the point that if you were to go to presearch.org is instantly redirects you to presearch.com!


Thanks for all of your suggestions and I hope things are looking a lot better!  :-D
